### ISSUE TITLE
replace [RSS] in archive

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-rssfeed#12]
Instead of leaving the [RSS] placeholder in the content of the campaign, wouldn't it make sense to replace it with the actual RSS content once sent? That way, the archive will have the actual RSS entries in the content.

What do you think?

**Comment by bramley** [comment]
Do you mean the View in Browser plugin? I'm just working on making that work with the RSS plugin and it should be released shortly.
The approach is to replace the [RSS] placeholder with the same RSS items as in the original email when the view in browser link is clicked. It needs to be like that because the link can be clicked while the campaign is still being sent out, and also so that a test message can be handled.

But replacing the placeholder with the actual items once the campaign has completed sending might be a good idea, as it then avoids a problem with viewing an old campaign whose RSS items have been purged. Is there a place in the code when a plugin will know that a campaign has definitely completed sending?

**Comment by michield** [comment]
Hmm, yes, it may need a new hook. The repeated campaign needs to keep the [RSS] otherwise it will start sending out the same campaign content. So, some hook at the moment where the repeated campaign is created might be where it can be done.

**Comment by michield** [comment]
This hook, https://github.com/phpList/phplist3/commit/f1d74203aa87e2bad123d9ca279e41cd4d16865c extended with https://github.com/phpList/phplist3/commit/e29e5ebd2c475986d8bacc89251c4022ec3bef08 may be interesting
