### ISSUE TITLE
Rss 2.0 problem

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-rssfeed#14]
Using the phpList.org RSS feed, we found an issue, which is caused by the Picofeed module.

https://www.phplist.org/feed/ has two "content" elements per feed item. One called "description" and the other one called "content".

Picofeed will take content over description, disregarding the description element completely.

https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Parser/Rss20.php#L207

As a result, the campaign with the feed has the complete page content of the item, instead of just a summary with the link. 

I tried to look, but Picofeed has no "config option" to change this behaviour. 

It would be nice to be able to use eg [DESCRIPTION] and [CONTENT] as item template placeholders to choose which one to add in the feed.

I'm not sure how to proceed on this. A PR to Picofeed will take a long time, provided they even accept it. Maybe using a different Feed parser?

**Comment by michield** [comment]
See also https://mantis.phplist.org/view.php?id=17945

**Comment by bramley** [comment]
From what I can see `<content:encoded>` isn't a standard RSS 2 element, as described here http://cyber.law.harvard.edu/rss/rss.html#hrelementsOfLtitemgt although it is valid to include extra elements.

Are you able to stop wordpress from including that element in the feed? It seems odd to include the full articles in a summary feed.

The picofeed content() method is feed-independent, so works with RSS 2, RSS 1, and atom feeds. Otherwise the plugin would need to have code specific to each feed, as description is not a valid element for atom.

**Comment by samtuke** [comment]
Have you two seen: https://github.com/fguillot/picoFeed/pull/133#issuecomment-93589585 ?

**Comment by michield** [comment]
I was trying to see if WP could be told not to use the two fields, but that seems hard coded.  But even then, Pico should not use it, and use description instead.

Looks like Sam found something interesting

**Comment by samtuke** [comment]
@michield in the thread I linked, my old colleague Raydiation goes through the same problem; apparently the description can be easily accessed via `$item->getTag('description');`

**Comment by michield** [comment]
Cool, @bramley in that case, what do you think about changing the call for "getContent" to the getTag('description') one?

**Comment by bramley** [comment]
The description element is specific to RSS 2 and I think RSS 1, and not valid for atom which does use a content element.
I don't know enough about the background to the encoding element, but may be you can look for an alternative way to generate the feed in wordpress. Can it generate an atom feed, or put the description in the encoded field?
Other RSS 2 feeds don't have that element, such as http://feeds.bbci.co.uk/news/rss.xml?edition=uk

**Comment by michield** [comment]
The thing is, the WP feed is the out of the box one, so we can change it here, but it would fail with every other WP install. Considering that the proposal is to drop the non-standard "content" field and use the common "description" one instead, that seems quite safe. I guess it would have to be done for RSS2 only, so that it won't interfere with Atom.

**Comment by samtuke** [comment]
As I understand it, picoFeed  uses `findItemContent()`  to first fetch content from RSS, and as a backup plan  fetches the description.  It seems that you need to do the opposite in order to accommodate  Feeds  which don't have the description tag. Would an if() empty() conditional statement be sufficient to achieve this?

**Comment by bramley** [comment]
Of course it is feasible, and quite trivial to implement, but I'm just wondering whether "it is a good idea".

**Comment by bramley** [comment]
On reflection it is a reasonable idea and will push a new release shortly.
The change is to use the description element if present (implicitly for an RSS feed), or use the summary element if present (implicitly for an atom feed. Otherwise use the picofeed content() method.

I have also updated picofeed to its latest release so you will also need to upgrade Common Plugin.

**Comment by samtuke** [comment]
Awesome :) Good luck.
