### ISSUE TITLE
PubSubHubbub 

### ISSUE THREAD

**Issue by schultzter** [bramley/phplist-plugin-rssfeed#3]
Have you considered PuSH (or PubSubHubbub) so that emails could be sent out every time there's a new entry in the RSS feed? Kind of like Blogtrottr but with better list management and analytics.

**Comment by bramley** [comment]
I hadn't previously heard of PubSubHubbub but I'm not sure how well your suggestion would work with phplist due to the potentially large number of campaigns that might be sent in one day. 

The aim of the plugin is to provide a way of disseminating content on a periodic basis, so sending a campaign when there is a single new item doesn't really fit.

**Comment by schultzter** [comment]
I agree it could lead to a lot of messages being sent, but that may be the point! I run a web site for a community swimming pool. The lifeguards can post a message on the front page (reminders, closures, cancellations, etc) and I'd like members to be emailed immediately'ish when such a message is posted. I'm trying to get it setup with Blogtrottr, but if I could leverage the same mailing list I use for regular weekly mailings as well, especially since I can control the mailing list and help people who are having trouble (with Blogtrottr they are on their own, I have no control). Thanks,

**Comment by bramley** [comment]
I can see a possible benefit in using this approach to get feed items instead of periodically polling, but I am still not convinced by the idea of sending a campaign immediately a new feed item has been received.
Sorry, but as I don't have a need for this myself I am not going to work on it.
