### ISSUE TITLE
[BUG] Table of content not working for define('CLICKTRACK', 0);

### ISSUE THREAD

**Issue by talgalili** [bramley/phplist-plugin-rssfeed#33]
When setting 
`define('CLICKTRACK', 1);`
The table of content links are broken (link to `http://?utm_source=phpList&utm_medium=email&utm_campaign` etc.)

**Comment by bramley** [comment]
It looks to be a problem with phplist when adding the google analytics parameters.

When click tracking is enabled that is done when the link is clicked. The TOC links are excluded from click tracking because their URLs do not begin with "http", therefore they do not have the analytic parameters added.

When click tracking is disabled, the analytics parameters are added to all links, including the TOC links.

You can make a small change to the phplist file admin/sendemaillib.php at line 616 to ignore link URLs that begin with '#' when adding analytic parameters

        for ($i = 0; $i < count($links[3]); ++$i) {
            if (substr($links[3][$i], 0, 1) == '#') {
                continue;
            }

I'll see whether there is a way for the plugin to handle this, but I think not.

Also, the analytic parameters include the campaign subject before placeholders have been replaced, which doesn't look very good or even useful. e.g.

`This+e-mail+has+[rss%3An]+new+posts+for+you%2C+[rssitem%3Atitle]%2C+and+[rss%3An-1]+more`

**Comment by talgalili** [comment]
Thanks Duncan,
I'll try it later.
Would you propose a PR to phplist on it?

**Comment by bramley** [comment]
This problem is fixed by this change to phplist https://github.com/phpList/phplist3/pull/810
